### ISSUE TITLE
Not an issue - it's my wish: Can you create .dll to enable free chat?

### ISSUE THREAD

**Issue by tedomedo** [Glatrix/AmongUsCosmetic#3]
I play 2022.3.29s but i don't find working free chat unlocker. Please, create it. Not .exe. I'd like something related to cheat engine - .CETRAINER or .dll.

**Comment by Glatrix** [comment]
https://www.unknowncheats.me/forum/among-us/498281-external-rework.html
![image](https://user-images.githubusercontent.com/73367967/171964132-d5a40e9b-4d55-43ae-b569-34f9619b8479.png)

**Comment by Glatrix** [comment]
Already have a menu with this feature and many more, on UnkownCheats
